title: my site
author: wbm92x
email: xxx
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site!!
  :trollface:

# social links
twitter_username: xxx
github_username:  wbm92x

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
